language: python
python:
  - 3.8
install:
  - pip install -r requirements-dev.txt
script:
  - set -eo pipefail
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - GSCIO_GOOGLE_TEST_BUCKET="gs-chunked-io-test"
